Architecture:
  Backbone:
    model_name: small
    name: MobileNetV3
    scale: 0.5
    small_stride:
    - 1
    - 2
    - 2
    - 2
  Head:
    fc_decay: 1.0e-05
    name: CTCHead
  Neck:
    encoder_type: rnn
    hidden_size: 48
    name: SequenceEncoder
  Transform: null
  algorithm: CRNN
  model_type: rec
Eval:
  dataset:
    data_dir: .
    image_dir: cuts
    label_file_list:
    - plates_labels.txt
    name: SimpleDataSet
    transforms:
    - DecodeImage:
        channel_first: false
        img_mode: BGR
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 32
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    batch_size_per_card: 16
    drop_last: false
    num_workers: 8
    shuffle: false
Global:
  cal_metric_during_train: true
  character_dict_path: custom_dict.txt
  character_type: en
  checkpoints: null
  epoch_num: 500
  eval_batch_step:
  - 0
  - 2000
  infer_img: null
  infer_mode: false
  log_smooth_window: 20
  max_text_length: 25
  pretrained_model: null
  print_batch_step: 10
  save_epoch_step: 3
  save_inference_dir: null
  save_model_dir: ./output/rec_multi_language_lite
  use_gpu: false
  use_space_char: true
  use_visualdl: false
Loss:
  name: CTCLoss
Metric:
  main_indicator: acc
  name: RecMetric
Optimizer:
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.001
    name: Cosine
  name: Adam
  regularizer:
    factor: 1.0e-05
    name: L2
PostProcess:
  character_dict_path: custom_dict.txt
  name: CTCLabelDecode
Train:
  dataset:
    data_dir: .
    image_dir: cuts
    label_file_list:
    - plates_labels.txt
    name: SimpleDataSet
    transforms:
    - DecodeImage:
        channel_first: false
        img_mode: BGR
    - RecAug: null
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 32
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    batch_size_per_card: 16
    drop_last: true
    num_workers: 8
    shuffle: true
